### PR TITLE
[5.x] Ensure jQuery for scrollTo

### PR DESCRIPTION
**Pull request by driesvints**
Seems this was an oversight in the previous PR.

### CODE REVIEW

**Comment by mbardelmeijer** [comment]
Thanks @driesvints! 💪

**Comment by lk77** [comment]
Hello,
since this change,
i have an error :
```
javascript error: $ is not defined
```
dusk should inject jquery no ,?

**Comment by lk77** [comment]
Hello,

can you tag this to 5.6.1 ?

thanks.

**Comment by driesvints** [comment]
@lk77 will tag tomorrow on release day.

**Pull request merged**
