### PR TITLE
Fix issue 614

### LINKED ISSUE #614: Error after upgrading to Laravel 5.8
After updating to Laravel 5.8, when running php artisan dusk, I get:

Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Dotenv\Dotenv::__construct() must be an instance of Dotenv\Loader, string given, called in /vendor/laravel/dusk/src/Console/DuskCommand.php on line 208

### PR DESCRIPTION
**Pull request by eXorus**
Fix #614

### CODE REVIEW

**Comment by staudenmeir** [comment]
This doesn't work with Laravel 5.7. The `Dotenv::create()` method doesn't exist in `vlucas/phpdotenv:^2.2`.

**Comment by eXorus** [comment]
So we should add a dependency to laravel 5.8 because Dusk are not compatible with Laravel 5.8 anymore ?

**Comment by staudenmeir** [comment]
What dependency do you mean?

**Comment by eXorus** [comment]
Dusk 5.0 for Laravel 5.7
Dusk 6.0 for Laravel 5.8

**Comment by driesvints** [comment]
Released v5.0.1 which should fix this.

**Pull request closed without merging**
