### PR TITLE
[6.x] add Chrome driver auto detection

### PR DESCRIPTION
**Pull request by browner12**
Using the `--detect` flag, the command will see if it can determine the install driver version, and then install the latest of that major version.

All credit goes to @staudenmeir. This code was taken from https://github.com/staudenmeir/dusk-updater.

In our next major release, I feel like this should be the default option, and we should add a `--latest` flag to get back to the current default behavior.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What does this do exactly? What do you mean by "determine the install driver version"?

**Comment by browner12** [comment]
sorry, should have said "the installed chromium version".

this checks the currently installed version of Chromium, and uses that to install the appropriate Driver version.

for example, on linux, it would run `chromium-browser --version`.

So let's say the installed version is 84.0.123.45.  `php artisan dusk:chrome-driver --detect` would install the appropriate driver for v84.

**Comment by driesvints** [comment]
@browner12 can you maybe also send in a PR to the docs for this?

**Comment by browner12** [comment]
sure thing

**Pull request merged**
