### PR TITLE
[6.x] PHP 8 Support

### PR DESCRIPTION
**Pull request by driesvints**

### CODE REVIEW

**Comment by viezel** [comment]
@driesvints is this also being tagged on Tuesday?

**Comment by driesvints** [comment]
This shouldn't have been merged as this wasn't ready yet (see the build). It'll be tagged as soon as php-webdriver/webdriver has been patched (which I'm going to look into now).

**Comment by driesvints** [comment]
(I should have marked this PR as draft)

**Comment by viezel** [comment]
I see. the test matrix is off.

**Comment by driesvints** [comment]
Reverted this one for now and resubmitted a draft PR.

**Pull request merged**
