### PR TITLE
[1.0.13] Include custom browser with scaffolding to encourage custom assertion

### PR DESCRIPTION
**Pull request by deleugpn**
We always want more assertion than the framework offers. This is a way of making it easy for everyone to understand how easy it is to build your custom assertion.

#217 #209 #206 #189 all talks about other options of assertion.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't think I will include this out of the box. Let's just have docs on how to use Browser macros.

**Comment by browner12** [comment]
do we have docs on this @deleugpn ?

**Comment by deleugpn** [comment]
I didn't write any docs at the time of this because i didn't know how to use macros then. Now I understand what Taylor wanted. Macros rock

**Comment by browner12** [comment]
yah, i think I got 1 working for an assertion, now just trying to figure out the best place to register it. maybe we should add a suggestion to the docs?

**Pull request closed without merging**
