### PR TITLE
[4.0] Update Chromedriver

### PR DESCRIPTION
**Pull request by driesvints**
Chromedriver was out of date which was causing some issues.

Fixes https://github.com/laravel/dusk/issues/570

### CODE REVIEW

**Comment by driesvints** [comment]
Trying to figure out why the tests are failing.

**Comment by driesvints** [comment]
Almost certain it's related to this Travis issue with IPv6 not being enabled: https://github.com/travis-ci/travis-ci/issues/8891

**Comment by tentus** [comment]
This has turned out to be a breaking change for my team, but frustratingly, nailing down exactly what's actually going on has eluded us. 

Specifically on Windows (our Mac and Linux machines behave exactly as expected) we're experiencing occasional 500 errors while running our Dusk tests, with the logs indicating that somehow the `.env` wasn't loaded for a given request (requests adjacent to this have no such issue). We know it's specifically happening after updating the exe in this merge, and yes, we've doubled checked the php version, chrome version, everything else. These files are definitely messing our Windows dev up. Unfortunately, that's about all we can determine for sure: the specific placement of the 500 error varies, as does the total number of failures (usually two or three spread out across a hundred tests). 

Our best guess is that maybe it's something to do with the session changes mentioned in the https://chromedriver.storage.googleapis.com/2.45/notes.txt? I wouldn't have thought that would be enough to induce a 500, but after two business days of debugging we're at a loss.

**Comment by driesvints** [comment]
@tentus a Chromedriver upgrade shouldn't be breaking because it's just providing you with the latest environment to test on. If you're experiencing issues can you open up an issue so we can track them down and have a look at them?

**Pull request merged**
