### PR TITLE
[6.x] Fixed vueAttribute for older Vue 2.x projects

### PR DESCRIPTION
**Pull request by myMartek**

### CODE REVIEW

**Comment by myMartek** [comment]
The latest release contains a bug:

For vue 2.0 projects there is a `return el.__vue.'.$key.';'` statement even though the correct way to query vue is using `__vue**__**`

**Comment by driesvints** [comment]
Ping @derekmd

**Comment by derekmd** [comment]
Whoops, sorry, don't know how that snuck through.

**Comment by driesvints** [comment]
@derekmd no worries. Does the fix look good to you?

**Comment by derekmd** [comment]
Yup, it's good. Code snippet from pre-Vue 3 fixes:

https://github.com/laravel/dusk/blob/bc9fd27ea167746ba0616a7661e6b5bd4a80c472/src/Concerns/MakesAssertions.php#L1103-L1108

**Pull request merged**
