### PR TITLE
Revert fb67e61 and fix return type

### PR DESCRIPTION
**Pull request by staudenmeir**
Fixes https://github.com/laravel/dusk/issues/455

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't understand why all other assertions would return $this except for this one?

**Comment by staudenmeir** [comment]
Please reopen @taylorotwell.
fb67e61 broke the `assertQueryStringHas()` assertion when testing a `$value`.
The changed method is just a helper method for the "real" assertion which returns `$this` as expected.

**Comment by iadambrown** [comment]
Yes, `assertQueryStringHas()` calls `assertHasQueryStringParameter()`, but expects the `$output` array to assert against (`PHPUnit::assertEquals($value, $output[$name] ...);`).

However, since the `assertHasQueryStringParameter()` assertion is *also* listed in the docs, this could cause issues for those who are expecting `$this` to now be returned... so returning the array satisfies `assertQueryStringHas()`, but returning `$this` allows for further method chaining when calling `assertHasQueryStringParameter()` directly.

**Comment by staudenmeir** [comment]
Good point about the docs. But as a protected method you can't call it from the outside...

Shouldn't we just merge `assertHasQueryStringParameter()` into `assertQueryStringHas()`? It doesn't provide any additional functionality as a separate method.

**Pull request closed without merging**
