### PR TITLE
Added lightweight css selector library

### PR DESCRIPTION
**Pull request by lkmadushan**
- Sizzle is a lightweight css selector engine provided by jQuery community and a component of jQuery
- [sizzlejs](https://sizzlejs.com/)

### CODE REVIEW

**Comment by KKSzymanowski** [comment]
Why is using jQuery an issue for testing? It doesn't affect your application whatsoever and its loading time is nowhere near the booting time of phpunit and chromedriver. It's reliable, everyone knows how to use it, and everyone can easily debug it.

One issue which has to be addressed is possibility of conflict with other JS libraries registered under the dollar sign. This however has been already resolved with using `window.jQuery` instead of `window.$`.

Introducing a new, even 10x faster may cause more trouble than good, in my opinion.

**Comment by lkmadushan** [comment]
@KKSzymanowski Sizzle is a component of jQuery and also jQuery includes lot of unwanted things that don't need for testing

**Comment by fetzi** [comment]
If using a library is the way to go, I would also stick to jQuery. Otherwise I think rewriting to Vanilla JS would be a good solution.

**Comment by KKSzymanowski** [comment]
>Sizzle is a component of jQuery

I did not know that. I rest my case.

**Comment by taylorotwell** [comment]
What is the measurable difference in performance of using this vs just using jQuery. Please post results.

**Comment by lkmadushan** [comment]
@taylorotwell https://jsperf.com/jquery-vs-sizzle-performance-test

**Comment by taylorotwell** [comment]
So why don't we just update the jQuery code to do jQuery.find()

**Pull request closed without merging**
