### PR TITLE
[6.x] Fix `logout()` when using AuthenticateSession middleware

### LINKED ISSUE #825: Logout issue when using AuthenticateSession middleware
- Dusk Version: v6.7.0
- Laravel Version: v8.8.0
- PHP Version: v7.3.3
- Database Driver & Version: //

### Description:
Can't login the user twice if the application is using AuthenticateSession middleware (```\Illuminate\Session\Middleware\AuthenticateSession```) after using the ```->logout()``` Dusk method.

### Steps To Reproduce:
- Create an application with a login page that uses the ```web``` middleware group.
- In the ```app/Http/Kernel.php``` file uncomment ```\Illuminate\Session\Middleware\AuthenticateSession::class```
- Write a test like this:
```php
// 1
$this->browse(function (Browser $browser) {
    $browser
        ->visit(new LoginPage())
            ->type('@username', $this->credentials['email'])
            ->type('@password', $this->credentials['password'])
            ->click('@submit')
            ->assertPathIs('/admin/dashboard')
            ->assertAuthenticatedAs($this->admin, 'admin')
            ->logout('admin');
});

// 2
$this->browse(function (Browser $browser) {
    $browser
        ->visit(new LoginPage())
            ->type('@username', $this->credentials['email'])
            ->type('@password', $this->credentials['password'])
            ->click('@submit')
            ->assertPathIs('/admin/dashboard')
            ->visit(new LogoutPage())
            ->assertGuest('admin');
});
```
- In the ```// 2``` test the request passes through https://github.com/laravel/framework/blob/8.x/src/Illuminate/Session/Middleware/AuthenticateSession.php#L54 and since the middleware sees that the ```'password_hash_' . $guard``` in the session doesn't match with the ```$request->user()->getAuthPassword()``` it tries to logout the user again before the new login happens.

### PR DESCRIPTION
**Pull request by EmanueleCoppola**
Should fix #825

### CODE REVIEW

**Comment by driesvints** [comment]
We don't support two the same browser calls in the same test method. Dusk is meant to mimic a real life scenario and you only do one single request when navigating to a page and running assertions.

**Comment by taylorotwell** [comment]
@driesvints we don't?

**Comment by driesvints** [comment]
@taylorotwell calling HTTP requests twice in the same test method has always lead to edge cases and problems afaik.

**Comment by driesvints** [comment]
FYI: this wasn't related to double HTTP calls in the end.

**Pull request merged**
