### PR TITLE
updated bins

### PR DESCRIPTION
**Pull request by gemal**
Backport new binaries to 2.0 branch

### CODE REVIEW

**Comment by gemal** [comment]
@taylorotwell can you have a look?

**Comment by browner12** [comment]
I'm pretty sure they do not accept changes to these drivers from community contributors, due to the danger of people injecting nefarious code into the binary files.

but good to ping them when new drivers are available.

**Comment by taylorotwell** [comment]
We will fix it.

**Comment by taylorotwell** [comment]
@browner12 is correct only I or @themsaid can manage the bins.

**Pull request closed without merging**
